module.exports = [
  {
    id: 1,
    name: "Paracetamol 500mg",
    type: "medicine",
    category: "allopathic",
    displayCategory: "Pain & Fever",
    manufacturer: "Cipla Ltd",
    dosage: "Tablet",
    pack: "Strip of 10",
    description: "For relief from fever, headaches, and mild to moderate pain.",
    price: 25,
    availability: "In Stock",
    requires_prescription: false,
    image: "/images/brightlife.png",
    imageColor: "from-green-400 to-green-600",
    slug: "paracetamol-500mg",
  },
  {
    id: 2,
    name: "Amoxicillin 500mg",
    type: "medicine",
    category: "allopathic",
    displayCategory: "Antibiotic",
    manufacturer: "GSK Pharmaceuticals",
    dosage: "Capsule",
    pack: "Strip of 10",
    description: "Broad-spectrum antibiotic for bacterial infections.",
    price: 120,
    availability: "In Stock",
    requires_prescription: true,
    image: "/images/brightlife.png",
    imageColor: "from-purple-400 to-purple-600",
    slug: "amoxicillin-500mg",
  },
  {
    id: 3,
    name: "Cetirizine 10mg",
    type: "medicine",
    category: "allopathic",
    displayCategory: "Antihistamine",
    manufacturer: "Sun Pharma",
    dosage: "Tablet",
    pack: "Strip of 10",
    description: "For allergy relief, hay fever, and skin allergies.",
    price: 35,
    availability: "In Stock",
    requires_prescription: false,
    image: "/images/brightlife.png",
    imageColor: "from-green-400 to-green-600",
    slug: "cetirizine-10mg",
  },
  {
    id: 4,
    name: "Omeprazole 20mg",
    type: "medicine",
    category: "allopathic",
    displayCategory: "Acidity",
    manufacturer: "Dr. Reddy's",
    dosage: "Capsule",
    pack: "Strip of 10",
    description: "Proton pump inhibitor for acid reflux and ulcers.",
    price: 85,
    availability: "Limited Stock",
    requires_prescription: false,
    image: "/images/brightlife.png",
    imageColor: "from-orange-400 to-orange-600",
    slug: "omeprazole-20mg",
  },
  {
    id: 5,
    name: "Surgical Gloves",
    type: "surgical",
    category: "surgical",
    displayCategory: "Disposables",
    manufacturer: "HLL Lifecare",
    size: "Medium",
    pack: "Box of 100",
    description: "Sterile latex examination gloves, powder-free.",
    price: 450,
    availability: "In Stock",
    requires_prescription: false,
    image: "/images/logo2.png",
    imageColor: "from-teal-400 to-teal-600",
    slug: "surgical-gloves",
  },
  {
    id: 6,
    name: "Surgical Mask",
    type: "surgical",
    category: "surgical",
    displayCategory: "PPE",
    manufacturer: "3M",
    size: "Standard",
    pack: "Box of 50",
    description: "3-ply surgical mask with nose clip and ear loops.",
    price: 250,
    availability: "In Stock",
    requires_prescription: false,
    image: "/images/logo2.png",
    imageColor: "from-gray-400 to-gray-600",
    slug: "surgical-mask",
  },
  {
    id: 7,
    name: "Insulin Syringes",
    type: "surgical",
    category: "surgical",
    displayCategory: "Injectables",
    manufacturer: "BD Medical",
    size: "1ml",
    pack: "Box of 100",
    description: "Disposable insulin syringes with ultra-fine needles.",
    price: 180,
    availability: "In Stock",
    requires_prescription: true,
    image: "/images/logo2.png",
    imageColor: "from-pink-400 to-pink-600",
    slug: "insulin-syringes",
  },
  {
    id: 8,
    name: "Surgical Gauze",
    type: "surgical",
    category: "surgical",
    displayCategory: "Dressings",
    manufacturer: "Johnson & Johnson",
    size: "10cm x 10cm",
    pack: "Pack of 10",
    description: "Sterile surgical gauze for wound dressing.",
    price: 120,
    availability: "In Stock",
    requires_prescription: false,
    image: "/images/logo2.png",
    imageColor: "from-yellow-400 to-yellow-600",
    slug: "surgical-gauze",
  },
  {
    id: 9,
    name: "Digital Thermometer",
    type: "device",
    category: "devices",
    displayCategory: "Monitoring",
    manufacturer: "Dr. Morepen",
    features: "Fever alert, memory function",
    pack: "1 Piece",
    description: "Accurate digital thermometer with quick reading.",
    price: 299,
    availability: "In Stock",
    requires_prescription: false,
    image: "/images/logo1.png",
    imageColor: "from-red-400 to-red-600",
    slug: "digital-thermometer",
  },
  {
    id: 10,
    name: "BP Monitor",
    type: "device",
    category: "devices",
    displayCategory: "Monitoring",
    manufacturer: "Omron",
    features: "Automatic, memory for 2 users",
    pack: "1 Piece",
    description: "Automatic blood pressure monitor with cuff.",
    price: 1299,
    availability: "In Stock",
    requires_prescription: false,
    image: "/images/logo1.png",
    imageColor: "from-indigo-400 to-indigo-600",
    slug: "bp-monitor",
  },
  {
    id: 11,
    name: "Nebulizer Machine",
    type: "device",
    category: "devices",
    displayCategory: "Respiratory",
    manufacturer: "Rossmax",
    features: "Portable, mask included",
    pack: "1 Piece",
    description: "Compressor nebulizer for asthma and respiratory conditions.",
    price: 2499,
    availability: "Available on Order",
    requires_prescription: true,
    image: "/images/logo1.png",
    imageColor: "from-cyan-400 to-cyan-600",
    slug: "nebulizer-machine",
  },
  {
    id: 12,
    name: "Oximeter",
    type: "device",
    category: "devices",
    displayCategory: "Monitoring",
    manufacturer: "BeatLife",
    features: "SpO2 & Pulse rate",
    pack: "1 Piece",
    description: "Fingertip pulse oximeter with LED display.",
    price: 899,
    availability: "In Stock",
    requires_prescription: false,
    image: "/images/logo1.png",
    imageColor: "from-violet-400 to-violet-600",
    slug: "oximeter",
  },
];
